//
//  ProductMock.swift
//  Mercado LibreTests
//
//  Created by John Edward Narvaez Londono on 11/12/23.
//

import Foundation
@testable import Mercado_Libre

let product1: Product = Product(id: "1",
        title: "Example Title",
        condition: "New",
        thumbnailID: "thumbnailID1",
        catalogProductID: "catalogProductID1",
        listingTypeID: "listingTypeID1",
        permalink: "http://example.com/product/1",
        buyingMode: "Buying mode 1",
        siteID: "ML1",
        categoryID: "categoryID1",
        domainID: "domainID1",
        thumbnail: "http://example.com/product/1/thumb.png",
        currencyID: "US",
        orderBackend: 1,
        price: 29.99,
        originalPrice: 39,
        salePrice: "29.99",
        soldQuantity: 10,
        availableQuantity: 90,
        officialStoreID: 1,
        officialStoreName: "Official Store",
        useThumbnailID: true,
        acceptsMercadopago: true,
        tags: ["tag1", "tag2"],
        shipping: Shipping(storePickUp: true,
                           freeShipping: true,
                           logisticType: nil,
                           mode: nil,
                           tags: nil,
                           benefits: nil,
                           promise: nil),
        stopTime: "2023-01-01T12:34:56Z",
        seller: Seller(id: 984561,
                       nickname: "SONY",
                       carDealer: nil,
                       realEstateAgency: nil,
                       empty: nil,
                       registrationDate: nil,
                       tags: nil,
                       carDealerLogo: nil,
                       permalink: nil,
                       sellerReputation: nil),
        sellerAddress: SellerAddress(comment: nil,
                                     addressLine: nil,
                                     id: nil,
                                     latitude: nil,
                                     longitude: nil,
                                     country: nil,
                                     state: nil,
                                     city: nil),
        address: Address(stateID: "16546",
                         stateName: "Bariloche",
                         cityID: "9843651",
                         cityName: "Bariloche"),
        attributes: [Attribute(id: nil,
                               name: nil,
                               valueName: nil,
                               attributeGroupID: nil,
                               attributeGroupName: nil,
                               values: nil,
                               source: nil,
                               valueType: nil)],
        installments: Installments(quantity: 10,
                                   amount: 29.99,
                                   rate: 0,
                                   currencyID: "US"),
        winnerItemID: "1",
        catalogListing: true,
        discounts: "",
        promotions: ["Promotion 1"],
        inventoryID: "InventoryID1",
        variationsData: ["Variation1":
                          VariationsDatum(thumbnail: nil,
                                          ratio: nil,
                                          name: nil,
                                          picturesQty: nil,
                                          inventoryID: nil)])

let product2: Product = Product(id: "2",
        title: "Example Title 2",
        condition: "New",
        thumbnailID: "thumbnailID1",
        catalogProductID: "catalogProductID1",
        listingTypeID: "listingTypeID1",
        permalink: "http://example.com/product/1",
        buyingMode: "Buying mode 1",
        siteID: "ML1",
        categoryID: "categoryID1",
        domainID: "domainID1",
        thumbnail: "http://example.com/product/1/thumb.png",
        currencyID: "US",
        orderBackend: 1,
        price: 29.99,
        originalPrice: 39,
        salePrice: "29.99",
        soldQuantity: 10,
        availableQuantity: 90,
        officialStoreID: 1,
        officialStoreName: "Official Store",
        useThumbnailID: true,
        acceptsMercadopago: true,
        tags: ["tag1", "tag2"],
        shipping: Shipping(storePickUp: true,
                           freeShipping: true,
                           logisticType: nil,
                           mode: nil,
                           tags: nil,
                           benefits: nil,
                           promise: nil),
        stopTime: "2023-01-01T12:34:56Z",
        seller: Seller(id: 984561,
                       nickname: "SONY",
                       carDealer: nil,
                       realEstateAgency: nil,
                       empty: nil,
                       registrationDate: nil,
                       tags: nil,
                       carDealerLogo: nil,
                       permalink: nil,
                       sellerReputation: nil),
        sellerAddress: SellerAddress(comment: nil,
                                     addressLine: nil,
                                     id: nil,
                                     latitude: nil,
                                     longitude: nil,
                                     country: nil,
                                     state: nil,
                                     city: nil),
        address: Address(stateID: "16546",
                         stateName: "Bariloche",
                         cityID: "9843651",
                         cityName: "Bariloche"),
        attributes: [Attribute(id: nil,
                               name: nil,
                               valueName: nil,
                               attributeGroupID: nil,
                               attributeGroupName: nil,
                               values: nil,
                               source: nil,
                               valueType: nil)],
        installments: Installments(quantity: 10,
                                   amount: 29.99,
                                   rate: 0,
                                   currencyID: "US"),
        winnerItemID: "1",
        catalogListing: true,
        discounts: "",
        promotions: ["Promotion 1"],
        inventoryID: "InventoryID1",
        variationsData: ["Variation1":
                          VariationsDatum(thumbnail: nil,
                                          ratio: nil,
                                          name: nil,
                                          picturesQty: nil,
                                          inventoryID: nil)])
